networks:
  penpot:

volumes:
  penpot_postgres_v15:
  ssl_certs:

services:
  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    # ports:
    #   - "5432:5432"  # Expose PostgreSQL port to the host machine

    volumes:
      - /var/pgdata:/var/lib/postgresql/data
      - /home/app/aamu/data/ssl:/home/app/aamu/data/ssl:ro
      - ./files/postgres-entrypoint.sh:/postgres-entrypoint.sh

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    # Use the entrypoint script to configure SSL
    entrypoint: ["/postgres-entrypoint.sh"]

