networks:
  penpot:

volumes:
  penpot_postgres_v15:
  ssl_certs:

services:
  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    ports:
      - "5432:5432"  # Expose PostgreSQL port to the host machine

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount the entire Let's Encrypt directory

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    # Use the entrypoint script to configure SSL
    entrypoint: ["docker-entrypoint.sh"]
    command: [
      "postgres",
      "-c", "ssl=on",
      "-c", "ssl_cert_file=/etc/letsencrypt/live/aamu.app/fullchain.pem",
      "-c", "ssl_key_file=/etc/letsencrypt/live/aamu.app/privkey.pem",
      "-c", "ssl_ca_file=/etc/letsencrypt/live/aamu.app/chain.pem"
    ]

