#!/usr/bin/env bash

set -ex
corepack enable;
corepack install;
pnpm install --config.confirmModulesPurge=false;

# Build render wasm binary
pushd ../render-wasm;
./build
popd

pnpm run lint:scss;
pnpm run test;
