name: Build and Upload Penpot DEVELOP Bundle

on:
  schedule:
    - cron: '16 5-20 * * 1-5'

jobs:
  build-develop-bundle:
    uses: ./.github/workflows/build-bundle.yml
    secrets: inherit
    with:
      gh_ref: "develop"
