name: Build and Upload Penpot STAGING Bundle

on:
  schedule:
    - cron: '36 5-20 * * 1-5'

jobs:
  build-staging-bundle:
    uses: ./.github/workflows/build-bundle.yml
    secrets: inherit
    with:
      gh_ref: "staging"
